### ISSUE TITLE
해야할일 적어 두겠음 이렇게 쓰는게 맞는지 모르겠지만 좀 발전해 나가자

### ISSUE THREAD

**Issue by kimikitae** [MinseokGo/food-share-project#1]
1. html, css 폴더에서 이미지들 /src/assets으로 위치 변경
    옮긴 후에 css 파일에서 이미지 파일   EX)   background-image: url(/src/assets/login_lock_icon.png);
    와 같이 경로 수정
2. html, css 폴더에서 html, css 파일들 vue파일로 변경
    변경시 참고사항
    .vue 파일 이름 login 처럼 한단어 X -> loginView와 같이 2단어이상으로 해야함 이거 설정 가능한데 귀찮아서 원래 이름+View 붙일까 생각중 이건 고선생 의견도 피력 요망
    변환된 html 파일에 body안에 있는 내용을 <template>  "여기" </template>   "여기"로 코드 복사

하다가 모르는 부분은 loginView.vue 참고
vscode 자동 줄 정렬 커맨드 shift + option + f

필수!!커밋 할때 node modeul(이넘 ㅈㄴ 무거움) 올리지 말것(아마 자동으로 .gitignore깔림 그래도 이중 체크 할것)!!필수

폴더 구조
public/index.html
->/src/main.js 호출
->/src/App.vue 호출
->/src/component/loginView 호출

오류 뜰시 참고자료:https://carrotweb.tistory.com/109

**Comment by MinseokGo** [comment]
확인이요
